### PR TITLE
WIP: rm factory Parameter

### PR DESCRIPTION
**Pull request by wjmelements**
#### Changes
Unnecessary to store `address(this)` for `msg.sender`.
Reviewers @moodysalem

### CODE REVIEW

**Comment by wjmelements** [comment]
Preliminary gas results look good. The benefit will be higher in Berlin.

**Comment by NoahZinsmeister** [comment]
tests are failing, and in general we're less worried about deploy-time costs than run-time costs

**Comment by wjmelements** [comment]
> tests are failing, 
That's why it's a WIP


> and in general we're less worried about deploy-time costs than run-time costs

That's not the trade-off.

**Comment by wjmelements** [comment]
@NoahZinsmeister Rude to close a WIP. Is your code frozen?

**Comment by NoahZinsmeister** [comment]
yes

**Pull request closed without merging**
